server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cart_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=vishnu
spring.datasource.password=vishnu98

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring:
kafka:
bootstrap-servers: localhost:9092
producer:
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.springframework.kafka.support.serializer.JsonSerializer